import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.schabi.newpipe.extractor.*;
import org.schabi.newpipe.extractor.downloader.*;
import org.schabi.newpipe.extractor.stream.*;

/** Explicit opt-in host feasibility probe, never part of unit tests or the APK.
 * Uses the pinned, unmodified extractor; never reads browser cookies or logs signed URLs.
 */
public final class YoutubeSmoke {
    private static long deadline;
    private static int requests;
    public static void main(String[] args) {
        if (args.length != 1 || !args[0].equals("--live")) {
            throw new IllegalArgumentException("Explicit --live is required (three bounded public YouTube probes)");
        }
        NewPipe.init(new Downloader() {
            @Override public Response execute(Request request) throws IOException {
                if (++requests > 35 || System.nanoTime() > deadline) throw new IOException("Probe request/time budget reached");
                URI uri = URI.create(request.url());
                if (!uri.getScheme().equals("https")) throw new IOException("HTTPS required");
                HttpURLConnection connection = (HttpURLConnection) uri.toURL().openConnection();
                connection.setConnectTimeout(10000); connection.setReadTimeout(10000);
                connection.setRequestMethod(request.httpMethod());
                connection.setRequestProperty("User-Agent", "Mozilla/5.0");
                request.headers().forEach((name, values) -> values.forEach(value -> connection.addRequestProperty(name, value)));
                try {
                    if (request.dataToSend() != null) {
                        connection.setDoOutput(true);
                        try (OutputStream out = connection.getOutputStream()) { out.write(request.dataToSend()); }
                    }
                    int code = connection.getResponseCode();
                    InputStream input = code >= 400 ? connection.getErrorStream() : connection.getInputStream();
                    byte[] body;
                    if (input == null) body = new byte[0];
                    else try (input) {
                        body = input.readNBytes(8 * 1024 * 1024 + 1);
                        if (body.length > 8 * 1024 * 1024) throw new IOException("Probe response size limit");
                    }
                    return new Response(code, connection.getResponseMessage(), connection.getHeaderFields(),
                        new String(body, StandardCharsets.UTF_8), connection.getURL().toString());
                } finally { connection.disconnect(); }
            }
        });
        probe("SEARCH Rick Astley Never Gonna Give You Up", () -> {
            var search = ServiceList.YouTube.getSearchExtractor("Rick Astley Never Gonna Give You Up");
            search.fetchPage();
            long count = search.getInitialPage().getItems().stream().filter(item -> item instanceof StreamInfoItem).count();
            System.out.println("video_results=" + count);
            if (count == 0) throw new IOException("No video results");
        });
        for (String id : List.of("dQw4w9WgXcQ", "Y_5hEaDzAsE")) {
            probe("VIDEO https://www.youtube.com/watch?v=" + id, () -> {
                var video = ServiceList.YouTube.getStreamExtractor("https://www.youtube.com/watch?v=" + id);
                video.fetchPage();
                System.out.println("metadata=true duration_seconds=" + video.getLength());
                var captions = video.getSubtitles(MediaFormat.VTT);
                System.out.println("vtt_tracks=" + captions.size());
                for (var track : captions) System.out.println("caption_language=" + track.getLanguageTag() + " automatic=" + track.isAutoGenerated());
                var audio = video.getAudioStreams();
                System.out.println("audio_streams=" + audio.size());
                for (var stream : audio) System.out.println("audio_format=" + stream.getFormat() + " delivery=" + stream.getDeliveryMethod() + " direct_url=" + stream.isUrl());
                if (!captions.isEmpty()) {
                    Response caption = NewPipe.getDownloader().get(captions.get(0).getContent());
                    System.out.println("caption_http=" + caption.responseCode() + " vtt_header=" + caption.responseBody().stripLeading().startsWith("WEBVTT") + " chars=" + caption.responseBody().length());
                }
            });
        }
    }
    private interface Probe { void run() throws Exception; }
    private static void probe(String name, Probe action) {
        requests = 0; deadline = System.nanoTime() + 90_000_000_000L;
        System.out.println(name);
        try { action.run(); System.out.println("PROBE_PASS requests=" + requests); }
        catch (Exception e) {
            System.out.println("PROBE_FAIL type=" + e.getClass().getSimpleName() + " detail=" +
                String.valueOf(e.getMessage()).replaceAll("https?://\\S+", "[URL]") + " requests=" + requests);
        }
    }
}
